FROM node:24-alpine AS met-hub
WORKDIR /app
COPY ./package*.json /app/
RUN npm install --legacy-peer-deps
COPY esdist/be/main.js /app/
COPY esdist/fe/* /app/html/
COPY public/* /app/html/
COPY client/index.html /app/html/
RUN ln -sf /app/html/ /app/html/callback
RUN ln -sf /app/html/ /app/html/go
CMD ["node", "/app/main.js"]
