version: "3.7"

services:
  met-hub:
    build:
      context: .
      target: met-hub
    image: met-hub
    container_name: met-hub
    network_mode: host
  met-hub-store:
    build:
      context: .
      target: met-hub-store
    image: met-hub-store
    container_name: met-hub-store
    network_mode: host
#  nginx:
#    build:
#      context: .
#      target: met-hub-nginx
#    image: met-hub-nginx
#    container_name: met-hub-nginx
#    network_mode: host
