version: "3.7"

networks:
  met-hub-net:

services:
  met-hub:
    build:
      context: .
      target: met-hub
    image: met-hub
    container_name: met-hub
    depends_on:
      - redis
#      - postgres
    env_file:
      - met-hub.env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8089:8089"
    networks:
      - met-hub-net
  met-hub-store:
    build:
      context: .
      target: met-hub-store
    image: met-hub-store
    container_name: met-hub-store
    depends_on:
      - redis
      - postgres
    env_file:
      - met-hub.env
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - met-hub-net
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - met-hub-net
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - met-hub-net


#  nginx:
#    build:
#      context: .
#      target: met-hub-nginx
#    image: met-hub-nginx
#    container_name: met-hub-nginx
#    ports:
#      - "80:80"
#    networks:
#      - met-hub-net


#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - met-hub-net
#  kafka:
#    image: docker.io/bitnami/kafka:3.3
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    networks:
#      - met-hub-net

#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
