version: "3.7"

services:
  met-hub:
    build:
      context: .
      target: met-hub
    image: met-hub
    container_name: met-hub
    depends_on:
      - redis
      - postgres
    env_file:
      - met-hub.env
    network_mode: host
  met-hub-store:
    build:
      context: .
      target: met-hub-store
    image: met-hub-store
    container_name: met-hub-store
    depends_on:
      - redis
      - postgres
    env_file:
      - met-hub.env
    network_mode: host
  redis:
    image: redis
    container_name: redis
    network_mode: host
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=all"]
  nginx:
    build:
      context: .
      target: met-hub-nginx
    image: met-hub-nginx
    container_name: met-hub-nginx
    network_mode: host
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    network_mode: host
#  kafka:
#    image: docker.io/bitnami/kafka:3.3
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    network_mode: host

#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
