#!/bin/bash
# example: 01.05.2018 06:26:01 1Loznice 206 v024.4+21021.0000.012.0000000000

cdate=`date +"%d.%m.%Y %H:%M:%S"`
fdate=`date +"%d%m%Y"`
th=`/root/Adafruit_Python_DHT/examples/AdafruitDHT.py 22 11`
star=`expr index "${th}" "*"`
percent=`expr index "${th}" "%"`
phum=`expr index "${th}" "y" + 1`
tlen=`expr ${star} - 5 - 1`
hlen=`expr ${percent} - ${phum} - 1`
t=`echo ${th:5:${tlen}}`
h=`echo ${th:${phum}:${hlen}}`
if [ ${tlen} -eq 3 ]
then
	cline1="1Vonku teplota00${t}+00000.0000.000.0000000000"

else
	cline1="1Vonku teplota0${t}+00000.0000.000.0000000000"
fi
cline2="1Vonku vlhkost0${h}+00000.0000.000.0000000000"

echo "${cdate} ${cline1}" >> /root/.k/data/k_19_${fdate}
echo "${cdate} ${cline2}" >> /root/.k/data/k_20_${fdate}
echo "${th}" > /root/.k/data/k_th
