/* eslint-disable import/prefer-default-export */

import { IStationCfg } from "./stationCfg";
import { STATION_MEASUREMENTS_DESC } from "./stationModel";

export class StationGarni1025ArcusCfg implements IStationCfg {
  STATION_ID = "2";

  TABLE = `station_${this.STATION_ID}`;

  COLUMNS = [
    STATION_MEASUREMENTS_DESC.TEMPERATUREIN.col,
    STATION_MEASUREMENTS_DESC.HUMIDITYIN.col,
    STATION_MEASUREMENTS_DESC.PRESSURE.col,
    "pressureabs", // todo
    STATION_MEASUREMENTS_DESC.TEMPERATURE.col,
    STATION_MEASUREMENTS_DESC.HUMIDITY.col,
    STATION_MEASUREMENTS_DESC.WINDDIR.col,
    STATION_MEASUREMENTS_DESC.WINDSPEED.col,
    STATION_MEASUREMENTS_DESC.WINDGUST.col,
    STATION_MEASUREMENTS_DESC.RAINRATE.col,
    STATION_MEASUREMENTS_DESC.SOLAR.col,
    STATION_MEASUREMENTS_DESC.UV.col,
    STATION_MEASUREMENTS_DESC.EVENTRAIN.col,
    STATION_MEASUREMENTS_DESC.HOURLYRAIN.col,
    STATION_MEASUREMENTS_DESC.DAILYRAIN.col,
    STATION_MEASUREMENTS_DESC.WEEKLYRAIN.col,
    STATION_MEASUREMENTS_DESC.MONTHLYRAIN.col,
  ];

  SOCKET_CHANNEL = `station_${this.STATION_ID}`;

  SOCKET_TREND_CHANNEL = `station_${this.STATION_ID}-trend`;

  REDIS_LAST_DATA_KEY = `station_${this.STATION_ID}-last`;

  REDIS_MINUTE_DATA_KEY = `station_${this.STATION_ID}-minute-data`;

  REDIS_STORE_CHANNEL = `station_${this.STATION_ID}-store-pubsub`;

  REDIS_TREND_KEY = `station_${this.STATION_ID}-trend`;
}
